import { execFileSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { parseEnv } from "node:util";
import { GENERATED_ENV, ROOT } from "./constants.mjs";

const MARKER = "# Generated by scripts/staging/prepare-env.mjs";

export function discoverSourceEnv() {
  const explicit = process.argv.find((arg) => arg.startsWith("--source="))?.slice(9);
  if (explicit) return resolve(explicit);
  if (existsSync(resolve(ROOT, ".env"))) return resolve(ROOT, ".env");
  const output = execFileSync("git", ["worktree", "list", "--porcelain"], {
    cwd: ROOT,
    encoding: "utf8",
  });
  const mainRoot = output.match(/^worktree (.+)$/m)?.[1];
  return resolve(mainRoot ?? ROOT, ".env");
}

export function buildStagingEnv(source) {
  const hasGateway = Boolean(source.AI_GATEWAY_API_KEY && source.AI_GATEWAY_BASE_URL);
  const hasAnthropic = Boolean(source.ANTHROPIC_API_KEY);
  if (!hasGateway && !hasAnthropic) {
    throw new Error("根 .env 缺少真实文本模型配置(AI Gateway 或 Anthropic)");
  }
  const keep = [
    "AI_GATEWAY_BASE_URL",
    "AI_GATEWAY_API_KEY",
    "ANTHROPIC_API_KEY",
    "ANTHROPIC_BASE_URL",
    "AI_ANTHROPIC_THINKING",
    "AI_ANSWER_MODEL",
    "AI_SUMMARIZE_MODEL",
    "AI_ANSWER_MAX_TOKENS",
    "AI_SUMMARIZE_MAX_TOKENS",
    "AI_ANSWER_INPUT_MICROS",
    "AI_ANSWER_OUTPUT_MICROS",
    "AI_SUMMARIZE_INPUT_MICROS",
    "AI_SUMMARIZE_OUTPUT_MICROS",
  ];
  const env = Object.fromEntries(
    keep.filter((key) => source[key]).map((key) => [key, source[key]]),
  );
  const password = randomBytes(16).toString("hex");
  return {
    ...env,
    POSTGRES_USER: "docpilot_staging",
    POSTGRES_PASSWORD: password,
    POSTGRES_DB: "docpilot_staging",
    DATABASE_URL: `postgres://docpilot_staging:${password}@postgres:5432/docpilot_staging`,
    DATABASE_POOL_MAX: "10",
    REDIS_URL: "redis://redis:6379",
    API_PORT: "3001",
    WEB_ORIGIN: "http://localhost:3300",
    BETTER_AUTH_URL: "http://localhost:3301",
    BETTER_AUTH_SECRET: randomBytes(32).toString("hex"),
    NEXT_PUBLIC_API_URL: "http://localhost:3301",
    NEXT_PUBLIC_APP_URL: "http://localhost:3300",
    S3_ENDPOINT: "http://minio:9000",
    S3_REGION: "us-east-1",
    S3_ACCESS_KEY_ID: "docpilot-staging",
    S3_SECRET_ACCESS_KEY: randomBytes(24).toString("hex"),
    S3_BUCKET: "docpilot-staging-private",
    S3_FORCE_PATH_STYLE: "true",
    SMTP_HOST: "mailpit",
    SMTP_PORT: "1025",
    MAIL_FROM: "DocPilot Staging <no-reply@staging.local>",
    OPENAI_BASE_URL: "http://ollama:11434/v1",
    AI_EMBEDDING_MODEL: "bge-m3",
    AI_EMBEDDING_MICROS: "0",
    WORKER_CONCURRENCY: "1",
    WORKER_REPLICAS: "1",
    OUTBOX_POLL_INTERVAL_MS: "500",
    RAG_MIN_SCORE: "0",
    LOG_LEVEL: "info",
  };
}

export function serializeEnv(env) {
  const lines = Object.entries(env).map(
    ([key, value]) => `${key}=${String(value).replace(/\n/g, "")}`,
  );
  return `${MARKER}\n${lines.join("\n")}\n`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const sourcePath = discoverSourceEnv();
  if (!existsSync(sourcePath)) throw new Error(`找不到源环境文件:${sourcePath}`);
  if (existsSync(GENERATED_ENV) && !readFileSync(GENERATED_ENV, "utf8").startsWith(MARKER)) {
    throw new Error(`拒绝覆盖非 Staging 生成的文件:${GENERATED_ENV}`);
  }
  const env = buildStagingEnv(parseEnv(readFileSync(sourcePath, "utf8")));
  writeFileSync(GENERATED_ENV, serializeEnv(env), { mode: 0o600 });
  console.log(`Staging env 已生成:${GENERATED_ENV}`);
  console.log(`真实文本接线:${env.AI_GATEWAY_API_KEY ? "AI Gateway" : "Anthropic"}`);
  console.log("Embedding 接线:本机 Ollama bge-m3");
}
